site_name: Doku
site_description: Demo Site description
site_author: ami und marci
site_url: https://xchwihan.github.io/
dev_addr: 127.0.0.1:9000
theme:
  name: "mkdocs"
repo_name: xchwihan/xchwihan.github.io
repo_url: https://github.com/xchwihan/xchwihan.github.io
markdown_extensions:
  - toc
  - extra
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
nav:
    - "Home": "index.md"
    - "Section 1":
      - "Section 1 Page 1": "section-01/page-01.md"
    - "Section 2":
      - "Section 2 Page 1": "section-02/page-01.md"
